### ISSUE TITLE
Bug: Collections not appearing in Sidebar but do when using a Project's dropdown menu

### ISSUE THREAD

**Issue by gitatmax** [getdepot/depot#11]

**Comment by destari** [comment]
Are these new collections that were added, or the default collections?  Also, any other debug or steps would be great!

**Comment by gitatmax** [comment]
As far I can tell, these are the default ones and newly added collections; nothing's appearing in the sidebar when I toggle it. I've tried rebooting the app and even rebooting the computer. Please let me know if there's anything I can do to help troubleshoot!

**Comment by destari** [comment]
What version of macOS are you running?

**Comment by destari** [comment]
Also, screenshots would be great!

**Comment by gitatmax** [comment]
@destari Of course! I'm on macOS Monterey Version 12.0 Beta (21A5294g). From the sidebar (toggled to display) and Collections preferences:

<img width="851" alt="CleanShot 2021-07-30 at 10 32 45@2x" src="https://user-images.githubusercontent.com/7244793/127668613-9e6f1a82-86aa-45e0-80b9-18c8ff76e8c3.png">
<img width="198" alt="CleanShot 2021-07-30 at 10 32 28@2x" src="https://user-images.githubusercontent.com/7244793/127668649-9e0a125e-eab4-4598-a13b-803c8e2f496f.png">
