### ISSUE TITLE
[BUG] Wont let me a new project to any collection

### ISSUE THREAD

**Issue by renegadecitizen** [getdepot/depot#12]
**Describe the bug**
Wont let me a new project to any collection

**To Reproduce**
1. Add new collection
2. add new project

**Expected behavior**
the window appears then immediately disappears.

**Screenshots**
the screen just disappears too fast

**Mac (please complete the following information):**
 - OS: Big Sur
 - Version 11.4
 - MacBook Pro (Retina, 15-inch, Late 2013)

**Comment by destari** [comment]
Thanks for reporting this!  I have reproduced the bug, and am working on a fix.

**Comment by renegadecitizen** [comment]
Thank you!

**Comment by destari** [comment]
I believe I have found and fixed the bug, will ship a new version to the App Store shortly!

**Comment by renegadecitizen** [comment]
Awesome good work man
I think the app has a lot of potential

**Comment by destari** [comment]
Submitted version 1.1.1 to the App Store, hopefully it is approved and released shortly!
and, thanks!  Happy to hear ideas, suggestions, and of course any bug reports!
