### ISSUE TITLE
[BUG] Thingiverse connection broken

### ISSUE THREAD

**Issue by langerdennis** [getdepot/depot#15]
**Describe the bug**
After making the connection to thingiverse, I can see my likes and designs in the thingiverse area. However, this list is not updating as I am making any updates on the thingiverse website, no matter how often I refresh or sign out and sign in again from Depot. The only way to re-populate that list with additional objects is to revoke app access from Depot through the thingiverse website and re-establishing the connection from scratch. Furthermore, downloads are not working, but stuck at 0% indefinitely.

**To Reproduce**
1. Go to 'Thingiverse'
2. Click on anything
3. Try to download

**Expected behavior**
Update the list of items automatically or at least when hitting "Refresh" in the thingiverse options screen.

**Screenshots**
<img width="1012" alt="Bildschirmfoto 2021-12-10 um 14 19 24" src="https://user-images.githubusercontent.com/70020435/145580434-aac8a331-e52b-41ac-9b58-fc2974fb1d5b.png">

**Mac (please complete the following information):**
 - OS: [Monterey]
 - Version [12.0.1]

**Additional context**
-

**Comment by destari** [comment]
Thanks for the bug report and screenshot!  I'll take a look at this and see what's going on, and ask for further input possibly too.

**Comment by destari** [comment]
I'm having difficulty reproducing this.. any way you can run the app and then get logs from Console.app ?  If that is too tricky, let me know and perhaps I can put some details together.

**Comment by langerdennis** [comment]
Hi Eric, unfortunately I am now travelling and will not return to my desk until New Year‘s - will get onto it as soon as I am back! Sorry for the delay and enjoy the holidays!

**Comment by destari** [comment]
No worries, have a great holiday!  Thanks!

**Comment by langerdennis** [comment]
Hi,

I have now opened Depot, started to capture logs, hit the "Refresh" button in the thingiverse section of preferences and captured the output of processes "Depot" and "runningboard" - let me know if you are looking for other logs. I only find "200" responses on the Depot tasks...
[thingiverse.log](https://github.com/getdepot/depot/files/7796530/thingiverse.log)

I have made another observation though. When I signed out of Thingiverse from within Depot and tried to log in again, I am getting the screenshotted error message. Once I remove the connection to the Depot app in my thingiverse account, I can create a new initial connection from Depot and my "likes" and "designs" are populated properly. Therefore the initial connection seems to always work correctly, but additional refreshes don't. It has worked once though - a design I have liked yesterday appeared in Depot sometime today. Could it be that it just takes time to refresh and only forced sync is not working? If so, at what interval should I expect new likes on thingiverse to appear in the Depot app?

<img width="1022" alt="Bildschirmfoto 2021-12-31 um 16 33 39" src="https://user-images.githubusercontent.com/70020435/147830905-09b8a84f-3cec-4fdb-8876-af501ba8c7b6.png">

**Comment by destari** [comment]
Thanks for the log and extra effort!
I believe this is a Thingiverse issue, unfortunately.  They appear to have a limit on the number of users that can use an app (that uses their API) until they approve it, which has been in the approval status for many months.  This is not documented anywhere, so this was unknown to me until these errors started popping up.

I have tried to contact Thingiverse several times, with ZERO response.  I have also tried Twitter, and contacting the parent company.  Please file a bug with them to help bring this to the top of their queue, otherwise I am not sure how to resolve it without violating their terms.

**Comment by langerdennis** [comment]
Thank you for following up! The answer makes sense, too bad thingiverse is working that way. I appreciate your effort though and cross my fingers the app will get approved at some point. I will just periodically re-establish the connection then as a workaround. I will close the bug and consider raising the issue at thingiverse!

**Comment by langerdennis** [comment]
Just as a quick update: Seems to be working now, no idea if the app was approved or some other magic happened... but seeing my likes populated very fast now!
