### ISSUE TITLE
[BUG] Library path settings not working

### ISSUE THREAD

**Issue by langerdennis** [getdepot/depot#16]
**Describe the bug**
Since I have all my stl-files in a folder structure on my local server, I want to store the Depot library on that server and replace or enhance the former folder structure (importing my stl-files as projects). I have set the library path through "preferences" --> "advanced" and also checked to copy items into the library. However, even after creating new projects I cannot find any library file on the network drive. I have also tested with local folders, which is not working for me either.

**To Reproduce**
1. Go to 'Preferences'
2. Click on 'Advanced'
3. Maintained path to attached storage
4. Find nothing in that folder

**Expected behavior**
I expect the Depot data to be maintained in the specified folder on my server, so I can properly backup and access.

**Screenshots**
-

**Mac (please complete the following information):**
 - OS: [Monterey]
 - Version [12.0.1]

**Additional context**
If there is any documentation on how this is supposed to work, happy to read that. This and my other issue are both critical requirements which made me purchase the app. Great work, but without these features I am so far better off with my folder structure. Hope this can be figured out!

**Comment by destari** [comment]
Ok, I see the issue.  This will take some time to solve correctly, I'll update this ticket when I believe I have it resolved.

**Comment by destari** [comment]
Ok, I believe I have fixed this, finally! A new version will be on the App Store "real soon"!

**Comment by langerdennis** [comment]
Perfect, thank you! The library file is now correctly stored following the path on my network drive. Just for clarification: The library file does contain all stl-files, right? Meaning as soon as folders are imported, everything is stored and not only referenced within the library file, making the imported stl-folders on the hard drive redunant? No problem with that, just want to make sure I understand how this works - thanks for fixing!

**Comment by destari** [comment]
That’s correct - all imported files, as well as the projects, tags, etc are all contained in the library file. Glad it’s working well for you!
