### ISSUE TITLE
Free trial?

### ISSUE THREAD

**Issue by sammcj** [getdepot/depot#17]
**Is your feature request related to a problem? Please describe.**

The app looks nice, but for $23 it's very pricey - especially when combined with the lack of trial.

**Describe the solution you'd like**

It would be good to at least have a free trial version available to test out.

**Describe alternatives you've considered**

Another option might be to reconsider the pricing model, $23 is a lot of money for a relatively simple app.

**Additional context**

**Comment by destari** [comment]
Hey Sam - you're right, it's too pricey.  I dropped the price a bunch, let's hope that lets more folks try it out. I'll look into a free trial too!

In the mean time, here's a one-time promo for you (I looked for your email address and could not find it on your website, etc).

TNRJWH43XWJX

**Comment by sammcj** [comment]
Hey Eric!

Oh wow that's awesome, thank you so much for the code - I'll definitely be trying it out this week and I'll drop you a donation or buy it for a friend if I find it useful.

I see the price is now $15 on the AU store - I think that's far more reasonable, thank you for considering this.

**Comment by destari** [comment]
No need to worry about a donation or buying it, I appreciate the feedback and the time it took you to do so!

**Comment by sammcj** [comment]
Thanks Eric, I'll definitely log some feature suggestions, if you don't agree with any of them please just feel to close them - I don't want to be demanding 😅.

(I'm completely new to 3d printing but within just a few days I've amounted a huge mess of files across multiple devices - I have a few ideas on what might help.)

By the way - I'll look into adding a contact form to my website, I had to remove my email as I'd get too much spam.

**Comment by destari** [comment]
This is exactly what led me to build Depot! To be honest, Depot pushed the limits of the available technology in macOS at the time of coding, and now that things have moved forward, I may go back and rebuild some large portions, so feedback is welcome!

**Comment by sammcj** [comment]
Hey @destari I've had a bit of a play and I've got quite a few ideas.

I don't want to overwhelm you, come off as demanding or spam the issues - I was thinking perhaps I'd just create one issue for feature suggestions and then you could pick which ones (if any) you'd like individual issues / feature requests for - does that work for you?

**Comment by destari** [comment]
Yea that works for me - as long as it is pretty clear what you are thinking, why, etc, and for any issues (bugs) call those out as clearly as you can.

Thanks!
